pipeline {
    agent any

    triggers {
        pollSCM('H/2 * * * *')
    }

    environment {
        VAULT_ADDR  = 'http://127.0.0.1:8200'
        VAULT_TOKEN = credentials('vault-token-streamora')
    }

    stages {
        stage('Pull latest code') {
            steps {
                dir('/opt/streamora') {
                    retry(3) { sh 'git pull origin main' }
                }
            }
        }

        stage('Write .env from Vault') {
            steps {
                dir('/opt/streamora') {
                    sh '''#!/bin/bash
                        set +x  # ไม่ print ค่า secret ใน log
                        get() { bao kv get -field="$2" "streamora/$1"; }

                        DB_PASS=$(get db password)
                        python3 - << PYEOF
import os, subprocess

def v(path, field):
    r = subprocess.run(
        ['bao','kv','get',f'-field={field}',f'streamora/{path}'],
        capture_output=True, text=True,
        env={**os.environ}
    )
    return r.stdout.strip()

lines = [
    "# Generated by Jenkins from Vault — do not edit manually",
    "APP_ENV=production",
    "LOG_LEVEL=INFO",
    "TOKEN_REFRESH_WORKER_ENABLED=true",
    "ALERT_EMAIL_TO=thanakornwannatong.tonkla@gmail.com",
    f"DATABASE_URL=postgresql+asyncpg://streamora:{v('db','password')}@db:5432/streamora",
    f"POSTGRES_USER=streamora",
    f"POSTGRES_PASSWORD={v('db','password')}",
    "POSTGRES_DB=streamora",
    f"TOKEN_ENCRYPTION_KEY={v('app','token_encryption_key')}",
    f"SECRET_KEY={v('auth','secret_key')}",
    f"JWT_SECRET_KEY={v('auth','jwt_secret_key')}",
    "JWT_ALGORITHM=HS256",
    "ACCESS_TOKEN_EXPIRE_MINUTES=30",
    f"GOOGLE_CLIENT_ID={v('google','client_id')}",
    f"GOOGLE_CLIENT_SECRET={v('google','client_secret')}",
    f"GITHUB_CLIENT_ID={v('github','client_id')}",
    f"GITHUB_CLIENT_SECRET={v('github','client_secret')}",
    "OAUTH_REDIRECT_BASE_URL=https://streamora.thana-wan.duckdns.org",
    f"LAZADA_APP_KEY={v('lazada','app_key')}",
    f"LAZADA_APP_SECRET={v('lazada','app_secret')}",
    "LAZADA_API_BASE_URL=https://api.lazada.co.th/rest",
    "LAZADA_AUTH_BASE_URL=https://auth.lazada.com/rest",
    "LAZADA_AUTHORIZE_URL=https://auth.lazada.com/oauth/authorize",
    "LAZADA_REDIRECT_URI=https://streamora.thana-wan.duckdns.org/api/v1/connections/lazada/callback",
    "LAZADA_COUNTRY=TH",
    "SHOPEE_PARTNER_ID=",
    "SHOPEE_PARTNER_KEY=",
    "SHOPEE_API_BASE_URL=https://partner.test-stable.shopeemobile.com",
    "SHOPEE_REDIRECT_URI=",
    "SHOPEE_WEBHOOK_URL=",
    "SHOPEE_DEFAULT_SHOP_ID=",
    "TIKTOK_APP_KEY=",
    "TIKTOK_APP_SECRET=",
    "TIKTOK_API_BASE_URL=https://open-api.tiktokglobalshop.com",
    "TIKTOK_REDIRECT_URI=",
    "SMTP_HOST=smtp.gmail.com",
    "SMTP_PORT=587",
    f"SMTP_USER={v('smtp','user')}",
    f"SMTP_PASSWORD={v('smtp','password')}",
    f"SMTP_FROM={v('smtp','user')}",
]

with open('.env', 'w') as f:
    f.write('\\n'.join(lines) + '\\n')
print(".env เขียนจาก Vault สำเร็จ")
PYEOF
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('/opt/streamora') {
                    sh 'docker compose -f docker-compose.prod.yml -f docker-compose.vps.yml up -d api'
                    sh 'sleep 3'
                    sh 'docker cp app/. streamora-api-1:/srv/app/'
                    sh 'docker compose -f docker-compose.prod.yml -f docker-compose.vps.yml restart api'
                }
            }
        }

        stage('Health check') {
            steps {
                sh 'sleep 10 && curl -f http://localhost:8000/api/v1/health || echo "เตือน: health check ไม่ผ่าน"'
            }
        }
    }

    post {
        success { echo 'Deploy สำเร็จ: streamora' }
        failure { echo 'Deploy ล้มเหลว เช็ค console log ด้านบน' }
    }
}
