pipeline {
    agent any

    triggers {
        pollSCM('H/2 * * * *')
    }

    environment {
        VAULT_ADDR  = 'http://127.0.0.1:8200'
        VAULT_TOKEN = credentials('vault-token-streamora')
    }

    stages {
        stage('Pull latest code') {
            steps {
                sh '''
                    git config --global --add safe.directory /opt/streamora
                    cd /opt/streamora && git pull origin main
                '''
            }
        }

        stage('Write .env from Vault') {
            steps {
                sh '''#!/bin/bash
                    set +x
                    v() { bao kv get -field="$2" "streamora/$1"; }

                    DB_PASS=$(v db password)
                    SMTP_USER=$(v smtp user)

                    cat > /opt/streamora/.env << ENVEOF
# Generated by Jenkins from Vault
APP_ENV=production
LOG_LEVEL=INFO
TOKEN_REFRESH_WORKER_ENABLED=true
ALERT_EMAIL_TO=thanakornwannatong.tonkla@gmail.com
DATABASE_URL=postgresql+asyncpg://streamora:${DB_PASS}@db:5432/streamora
POSTGRES_USER=streamora
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=streamora
TOKEN_ENCRYPTION_KEY=$(v app token_encryption_key)
SECRET_KEY=$(v auth secret_key)
JWT_SECRET_KEY=$(v auth jwt_secret_key)
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
GOOGLE_CLIENT_ID=$(v google client_id)
GOOGLE_CLIENT_SECRET=$(v google client_secret)
GITHUB_CLIENT_ID=$(v github client_id)
GITHUB_CLIENT_SECRET=$(v github client_secret)
OAUTH_REDIRECT_BASE_URL=https://streamora.thana-wan.duckdns.org
LAZADA_APP_KEY=$(v lazada app_key)
LAZADA_APP_SECRET=$(v lazada app_secret)
LAZADA_API_BASE_URL=https://api.lazada.co.th/rest
LAZADA_AUTH_BASE_URL=https://auth.lazada.com/rest
LAZADA_AUTHORIZE_URL=https://auth.lazada.com/oauth/authorize
LAZADA_REDIRECT_URI=https://streamora.thana-wan.duckdns.org/api/v1/connections/lazada/callback
LAZADA_COUNTRY=TH
SHOPEE_PARTNER_ID=
SHOPEE_PARTNER_KEY=
SHOPEE_API_BASE_URL=https://partner.test-stable.shopeemobile.com
SHOPEE_REDIRECT_URI=
SHOPEE_WEBHOOK_URL=
SHOPEE_DEFAULT_SHOP_ID=
TIKTOK_APP_KEY=
TIKTOK_APP_SECRET=
TIKTOK_API_BASE_URL=https://open-api.tiktokglobalshop.com
TIKTOK_REDIRECT_URI=
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=$(v smtp password)
SMTP_FROM=${SMTP_USER}
ENVEOF
                    echo ".env เขียนจาก Vault สำเร็จ"
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    cd /opt/streamora
                    docker compose -f docker-compose.prod.yml -f docker-compose.vps.yml up -d api
                    sleep 3
                    docker cp app/. streamora-api-1:/srv/app/
                    docker compose -f docker-compose.prod.yml -f docker-compose.vps.yml restart api
                '''
            }
        }

        stage('Health check') {
            steps {
                sh 'sleep 10 && curl -f http://localhost:8000/api/v1/health || echo "เตือน: health check ไม่ผ่าน"'
            }
        }
    }

    post {
        success { echo 'Deploy สำเร็จ: streamora' }
        failure { echo 'Deploy ล้มเหลว เช็ค console log ด้านบน' }
    }
}
